### PR TITLE
README.md: update link for libkeyfinder to Mixxx fork

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
Oh I had no idea there was a fork. I'll have to look closer at this since I maintain some libkeyfinder packages.

**Comment by evanpurkhiser** [comment]
I would like to keep the original attribution though, so maybe we can also make it clear that this one's the fork

**Comment by Be-ing** [comment]
The attribution is kept prominently in the fork's README.md and it still appears as a fork of the original repo on GitHub.

**Comment by evanpurkhiser** [comment]
Cool, sounds good. Thanks for this!

**Comment by Be-ing** [comment]
No problem. Some keyfinder-cli users contributed some nice improvements to the documentation for building libkeyfinder on macOS. I have [packaged it for vcpkg](https://github.com/microsoft/vcpkg/pull/15878) which we are using for Mixxx builds now.

By the way, this fork happened with @ibsh's approval. He gave me write access to the original repo and I decided to fork it to the mixxxdj organization.

**Comment by evanpurkhiser** [comment]
Oh! That's great to know, I'll have to look into this more! I also maintain https://github.com/EvanPurkhiser/keyfinder-py which is pretty much just this code

I also maintain a personal homebrew recipie for libkeyfinder https://github.com/EvanPurkhiser/homebrew-personal/blob/master/libkeyfinder.rb which I'll have to update, and maybe finally try to get merged into the master homebrew list

**Pull request merged**
